apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parasol-insurance

resources:
  - multi-model-dataconnection.yaml
  - multi-model-inference.yaml
  - multi-model-serving-runtime.yaml

