apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parasol-insurance

resources:
  - standard-workbench-dataconnection.yaml
  - standard-workbench-pvc.yaml
  - standard-workbench-notebook.yaml

